### ISSUE TITLE
Building Vagrant image - provisioner options

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aeon-ztps#106]
A few new build outputs are required for a number of projects upcoming (Openstack, KVM, Libvirt, ESXi) environments.

Right now, we build the vagrant image by hand, tweak as necessary, and export as an OVF, change OVF settings for compatibility between virtualbox and vmware.

This process is cumbersome and error-prone and not easily repeatable.
The ask for this is for the Vagrant build process to have build outputs for VirtualBox, libvirt (KVM, openstack, proxmox, etc), and vsphere.

**Comment by bobbywatson3** [comment]
This issue has been resolved with the apstra-packer tool.
