### ISSUE TITLE
Vagrantfile

### ISSUE THREAD

**Issue by burnyd** [Apstra/aeon-ztps#114]
Is missing require 'yaml' to make it start.

**Comment by bobbywatson3** [comment]
Hey Daniel! Can you give us a little more info on the problem that you're experiencing? What's not working, and how would you expect it to work?

**Comment by jpsenior** [comment]
It seems burny's request is to add the following to the top of the vagrantfile.
`require 'yaml'`

**Comment by jeremyschulman** [comment]
closing due to lack of information.
