### ISSUE TITLE
Add button to "ztp status" page to uninstall AOS run files

### ISSUE THREAD

**Issue by bobbywatson3** [Apstra/aeon-ztps#116]
invoke aos-installer-foo uninstall command from webui.

**Comment by jpsenior** [comment]
@bobbywatson3 my request for this as well is to send it to an 'uninstall' page with the device IP pre-filled: this way I can run the AOS uninstaller on a device that may not be currently registered to AOS.

I can write the UI part of this request if you've already started the uninstaller.

**Comment by jeremyschulman** [comment]
closing this as it is AOS specific.
