### ISSUE TITLE
Is there developer guide on how to support other vendor OS?

### ISSUE THREAD

**Issue by skg-net** [Apstra/aeon-ztps#118]
Is there developer guide on how to support other vendor OS?

**Comment by jeremyschulman** [comment]
@skg-net - I am in the process of putting one together.  If you'd like to be an "alpha pilot" as part of this process, please let me know.  Which OS are you looking at?

**Comment by skg-net** [comment]
@jeremyschulman Thanks for the quick response. Planning to add support for Dell OS9 / OS10. 
Its of personal interest and cannot give my commitment at this time, will get back to you on that. Please keep in loop, will try it out.

**Comment by jeremyschulman** [comment]
@skg-net - does this OS have a "ZTP" or similar process?  that is, something that is run by the OS on first/factory boot that kickstarts the system for zero-touch-provisioning; i.e. similar to Cumulus / Arista / Cisco|POAP, ....

Also, is there a VM for the OS that we could try out?

**Comment by skg-net** [comment]
Yes, it does support something similar to ZTP. Its called Bare Metal Provisioning  [(BMP)](http://en.community.dell.com/techcenter/networking/w/wiki/4478.dell-bare-metal-provisioning-3-0-automate-the-network). 
We have a VM as well, I need to check with Dell EMC Marketing to how get you one.

**Comment by jeremyschulman** [comment]
@skg-net - looking forward to your reply on this topic, any update?

**Comment by skg-net** [comment]
@jeremyschulman I am yet to get the response from Marketing. I will get back to you on that.

Can you send me the WIP document you got, so that I can get started?

**Comment by dgarros** [comment]
Hi @skg-net 

Following our discussion yesterday
I checked with @bobbywatson3 and we don't have a developer guide yet but it's high on Bobby's Todo list so hopefully we'll have something in 2-3 weeks.
Thanks for your patience, we are looking forward to add OS10 support on the ZTP server 

Damien

**Comment by skg-net** [comment]
Thanks @dgarros

**Comment by darien-hirotsu** [comment]
@jeremyschulman @dgarros - Hi! My coworkers and I have done quite a bit of work with OpenClos (ZTP) and Junos. In that vein, do you have Junos integration yet, and if not, are you looking for some community support? We have access to EX4300's and QFX5100's in our lab if that would help. Our team would love to contribute and participate in the alpha if that would be useful.

**Comment by jeremyschulman** [comment]
@darien-hirotsu - Thank you for your interest and offer!  We would love the community support on the EX and QFX Junos product lines.  I'll talk with the team today and ask someone to follow up!

**Comment by basilsaji-rtb** [comment]
@jeremyschulman  @bobbywatson3 Is this document available?

**Comment by bobbywatson3** [comment]
We had other things come up, and the developer guide has been de-prioritized, so we do not have anything to share at this time.

Having said that, I'd be glad to work with you to help out however I can.

**Comment by skg-net** [comment]
@bobbywatson3 @jeremyschulman Can you please let me know if the developer guide is available?

**Comment by bobbywatson3** [comment]
We still do not have a developers guide unfortunately. My advice would be to use the existing device code as a template, and please feel free to reach out to me directly if you'd like help or a quick overview.

**Comment by Noname2244** [comment]
Any news here? Any tips on how to get this working for ios xe 16.x.x ? Im looking at ways to deploy 3650 switches

**Comment by SMBurrows** [comment]
@Noname2244 Did you manage to get IOS-XE working?

**Comment by Ondjultomte** [comment]
No,no luck yet
