### ISSUE TITLE
Determine cumulus device type by something other than hostname

### ISSUE THREAD

**Issue by bobbywatson3** [Apstra/aeon-ztps#123]
Right now, when a cumulus device boots up, the ztp server checks the hostname to determine the device type. Hostnames change, but device types do not. I suggest that we find a way to determine the device type based on dhcp options, or the headers that are sent when the ztp script is requested.

**Comment by bobbywatson3** [comment]
Updated to reflect the fact that this only affects cumulus devices. For Arista and Cisco devices, we are determining device type by the dhcp option "vendor-class-identifier"

**Comment by jpsenior** [comment]
This is a technical limitation on the cumulus platform itself.  Cumulus has not implemented any 'vendor-class' identification features, even as late as v3.1.
An outstanding RFE is still in place at https://support.cumulusnetworks.com/hc/en-us/articles/201787676-DHCP-on-eth0-Does-Not-Send-Vendor-Data 

Technically speaking Aeon-ZTPs could just send the cumulus-provision-url option directly - it'll be ignored by devices that don't use it.

**Comment by jeremyschulman** [comment]
@bobbywatson3 - we should try @jpsenior suggestion.  I'll do this and report back.

**Comment by bobbywatson3** [comment]
@acarpi also stated that Cumulus switches may require different firmware images based on the chipset that they use. This is an unrelated issue, but it might not be a bad idea to see if that info is included in the DHCP options that are sent.

**Comment by jeremyschulman** [comment]
@bobbywatson3 (cc, @acarpi) - re: loading firmware based.  There is currently a mechanism to load different firmware based on the hardware model.  This is done via the "os-selector.cfg" file stored in within the "etc/profiles/.../<os-name>" folder.  Not sure if this mechanism addresses the issue; but please let me know.

**Comment by bobbywatson3** [comment]
@jpsenior The cumulus-provision-url option worked. This issue is resolved. Thanks!

**Comment by bobbywatson3** [comment]
Resolved in #144
