### ISSUE TITLE
Provide build/version info file in the VM

### ISSUE THREAD

**Issue by acarpi** [Apstra/aeon-ztps#128]
We should add a file (suggest /etc/aeon_vesion) containing build info about the Aeon ZTP VM. This could be useful when opening issues against Aeon-ztps.

An example could be something like this:

> $ cat /etc/aeon_vesion
> VERSION=0.4.0
> BUILD_ID=Aeon-0.4.0-45
> BRANCH_NAME=develop
> COMMIT_ID=ad5c181a3a5a2cd58e8adf634136aad310690a95
> BUILD_DATETIME=2016-12-08_13:03:25_PST

**Comment by bobbywatson3** [comment]
Good idea. Thanks @acarpi

**Comment by jpsenior** [comment]
Love this idea. Embed into UI as well.

Git hooks?

**Comment by jeremyschulman** [comment]
@acarpi - great idea, we'll definitely get this into the next spin.

**Comment by acarpi** [comment]
@jpsenior  no need for git hooks, usually CI tools can expose those info as env variables and you just need to pass them down to your build scripts. I can share how we do it for AOS if needed.

**Comment by bobbywatson3** [comment]
This needs to be added during the build, so this should be resolved in apstra-packer. Also, we are not building OVA/QCOW2 artifacts on a CI build server. The builds happen on a laptop. @acarpi perhaps we could configure jenkins to do this upon code merge? Let's chat online when you have a chance.

I will leave this issue open to track accessing and displaying version/build info, but generating and copying the file will be tracked elsewhere.

**Comment by jpsenior** [comment]
@bobbywatson3 I build aeon-ztps with 'vagrant up' and not packer, which is tracked separately from this repo.  As a customer / external user of Aeon-ZTPs who may not use packer, do we have options where we can include build information in a 'vagrant up' or other build process that is not integrated with Apstra's internal CI pipeline?

**Comment by bobbywatson3** [comment]
Why would a customer need anything more than the ztps version number? For internal development, it is useful for us to know what particular branch and commit an OVA was built from, but for external use, all builds will be from master with a tagged release.

**Comment by bobbywatson3** [comment]
Resolved
