### ISSUE TITLE
Remove unneeded boot services

### ISSUE THREAD

**Issue by acarpi** [Apstra/aeon-ztps#129]
From the list of services automatically enabled at boot, I think we could remove at least  virtualbox-guest-utils (I think we shouldn't be packaging with virtualbox-utils in the first place since those are hypervisor/version dependent) and open-iscsi.

> root@aeon-ztps:/home/admin# service --status-all
>  [ + ]  acpid
>  [ + ]  apparmor
>  [ + ]  apport
>  [ + ]  atd
>  [ - ]  bootmisc.sh
>  [ + ]  celeryd
>  [ - ]  checkfs.sh
>  [ - ]  checkroot-bootclean.sh
>  [ - ]  checkroot.sh
>  [ + ]  console-setup
>  [ + ]  cron
>  [ - ]  cryptdisks
>  [ - ]  cryptdisks-early
>  [ + ]  dbus
>  [ + ]  grub-common
>  [ - ]  hostname.sh
>  [ - ]  hwclock.sh
>  [ + ]  irqbalance
>  [ - ]  isc-dhcp-server
>  [ + ]  iscsid
>  [ + ]  keyboard-setup
>  [ - ]  killprocs
>  [ + ]  kmod
>  [ - ]  lvm2
>  [ + ]  lvm2-lvmetad
>  [ + ]  lvm2-lvmpolld
>  [ + ]  lxcfs
>  [ - ]  lxd
>  [ + ]  mdadm
>  [ - ]  mdadm-waitidle
>  [ - ]  mountall-bootclean.sh
>  [ - ]  mountall.sh
>  [ - ]  mountdevsubfs.sh
>  [ - ]  mountkernfs.sh
>  [ - ]  mountnfs-bootclean.sh
>  [ - ]  mountnfs.sh
>  [ + ]  networking
>  [ + ]  nginx
>  [ + ]  ondemand
>  [ + ]  open-iscsi
>  [ - ]  open-vm-tools
>  [ - ]  plymouth
>  [ - ]  plymouth-log
>  [ + ]  procps
>  [ + ]  rabbitmq-server
>  [ + ]  rc.local
>  [ + ]  resolvconf
>  [ - ]  rsync
>  [ + ]  rsyslog
>  [ - ]  screen-cleanup
>  [ - ]  sendsigs
>  [ + ]  ssh
>  [ + ]  udev
>  [ + ]  ufw
>  [ - ]  umountfs
>  [ - ]  umountnfs.sh
>  [ - ]  umountroot
>  [ - ]  unattended-upgrades
>  [ + ]  urandom
>  [ - ]  uuidd
>  [ + ]  uwsgi
>  [ + ]  virtualbox-guest-utils
>  [ - ]  x11-common
>  [ + ]  xinetd

**Comment by jpsenior** [comment]
Getting rid of cloud-init might be nice too.

**Comment by jeremyschulman** [comment]
@acarpi - we will track/manage this as part of the packing process; as done by a separate repo.  closing this issue.

@bobbywatson3 - please transfer this information to the appropriate packer related efforts.
