### ISSUE TITLE
Don't upgrade a cumulus switch if the image is already installed.

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aeon-ztps#133]
@acarpi is asking for an enhancement to prevent upgrading a cumulus switch if the target image is already installed.  The problem is on every sanitize in the test environment, ZTP is performing a full reinstall of cumulus.  This should be avoided.

**Comment by jeremyschulman** [comment]
@acarpi @jpsenior - the aeon-ztps system functions per your request, so this must be a setup related issue.  I am closing this ticket, and will follow up with @acarpi directly.
