### ISSUE TITLE
Documentation and/or flexibility of os-selector.conf

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aeon-ztps#134]
@acarpi requires multiple selection options to target image upgrades for specific platforms.  os-selector.conf should be able to detect the model name, image name, etc, and perform selective OS upgrades to specific platforms.

**Comment by jeremyschulman** [comment]
@acarpi - the aeon-ztps functions in this manner, and I expect that I need to show you how this is done.  Closing this ticket.
