### ISSUE TITLE
EOS bootstrap needs graceful init/check

### ISSUE THREAD

**Issue by jeremyschulman** [Apstra/aeon-ztps#136]
We have observed that the use the "--init-delay" value is not a good way to handle the reboot out of EOS ZTP process.  Therefore the eos-bootstrap program needs to handle this state change in a better way.  If this is not handled better the bootstrap will fail thinking that the device is operational when it is not.  Therefore this issue labeled as bug.

As a workaround, you can use the --init-delay value set to a high value, like 180 seconds

cc @acarpi

**Comment by bobbywatson3** [comment]
@acarpi Did your latest PR resolve this issue?

**Comment by acarpi** [comment]
As a side effect I believe yes. I guess the current init-delay value is 60s, which is good for me, and still my retry logic kicks in, so I guess this issue is taken care as well.
