### ISSUE TITLE
ztp-cumulus checks oldest DHCP lease for provision_url

### ISSUE THREAD

**Issue by bobbywatson3** [Apstra/aeon-ztps#145]
DHCP leases are added to /var/lib/dhcp/dhclient.eth0.leases from top to bottom, with the newest being on the bottom. Currently, ztp-cumulus.sh checks for the provision url in the top (oldest) dhcp lease. If the provision url was incorrect in that lease, and then later updated on the DHCP server, ztp-cumulus.sh would still use the old and incorrect provision url in the first lease.

ztp-cumulus.sh should start at the bottom of the leases file, and search backwards for the provision url.

**Comment by bobbywatson3** [comment]
Thanks for pointing this out, @acarpi

**Comment by bobbywatson3** [comment]
Code that needs to be updated to search from bottom of file backwards:

`provision_url=$(grep -m1 'cumulus-provision-url' /var/lib/dhcp/dhclient.eth0.leases | awk -F "/" '{print $3}')`

**Comment by bobbywatson3** [comment]
@acarpi suggested this instead:

`cat /var/lib/dhcp/dhclient.eth0.leases | grep 'cumulus-provision-url'| tail -1 | awk -F "/" '{print $3}'`

tail -1 will pick the last one

**Comment by acarpi** [comment]
Thank you for fixing this!
