### ISSUE TITLE
Aeon ZTP reports model "Cumulus-VX" for Ubuntu VMs

### ISSUE THREAD

**Issue by acarpi** [Apstra/aeon-ztps#148]
Trying to use Aeon ZTP to provide the 'finally' script only (no os-selector.cfg), the GUI reports the wrong hw model. See screenshot.

<img width="1289" alt="screen shot 2017-02-01 at 1 12 16 pm" src="https://cloud.githubusercontent.com/assets/528719/22526468/403dadce-e880-11e6-874a-8943060404f7.png">

**Comment by bobbywatson3** [comment]
resolved in Apstra/aeon-venos#18
