### ISSUE TITLE
Concurrent GETs to /api/devices can get HTTP Error 500

### ISSUE THREAD

**Issue by acarpi** [Apstra/aeon-ztps#161]
When Aeon ZTP API is dealing with multiple concurrent requests I get error 500

```
[2017-02-15 01:05:04,659] ERROR in app: Exception on /api/devices [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/aeon_ztp/api/views.py", line 144, in _get_devices
    items = [to_json.dump(rec).data for rec in db.query(models.Device).all()]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2613, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'SELECT devices.ip_addr AS devices_ip_addr, devices.os_name AS devices_os_name, devices.serial_number AS devices_serial_number, devices.hw_model AS devices_hw_model, devices.os_version AS devices_os_version, devices.state AS devices_state, devices.message AS devices_message, devices.created_at AS devices_created_at, devices.updated_at AS devices_updated_at \nFROM devices']
```

**Comment by jeremyschulman** [comment]
@acarpi - could you please provide more context; i.e. how many concurrent requests in which timeframe ? for example, 2 attempts in 5 seconds?  That would be helpful.  Thank you.

**Comment by acarpi** [comment]
Sure, this issue happened in our systest infra. Given a topology, when we issue a 'sanitize' command, this is spawning concurrent processes each taking care of triggering ZTP on a single DUT. In particular, we do the following

- remove the entry for that device from /api/devices, doing a DELETE /api/devices?ip_addr=<ip>
- write erase; reload
- GET /api/devices polling until the state is "DONE".

I think the issue occurs because DELETE is locking the DB, causing the error above when another process is doing a GET /api/devices. I've seen this happening for topologies of a few devices (e.g. 5-10). 

A workaround we have in place until this is fixed is to sleep a random interval between 2-5s before issuing the first DELETE, but this is only mitigating the issue, which sometimes (rarely) still appears in our infra.

Thanks

**Comment by jpsenior** [comment]
Guys, I believe this is implicit limitation of SQLite.  SQLite will block _all_ transactions including select if the database is locked for writing for any reason.  I've seen the same issues in our systest infra and some other network labs I have been building.  SQLAlchemy does enforce concurrency in a thread module by ensuring only one process has access to the database at the same time (reads, writes). For this project's use case, it's possible multiple processes have access to the file at the same time - multiple nginx proxies, celery UI scripts, other direct API calls.

I have a few proposals
a) Implementation of an in-memory proxy model to handle all GET requests, with a seperate trigger-based system to handle write (POST/DELETE), with a trigger to execute a reload of the in-memory proxy model after write is complete.

b) A simple migration to maridab for the aeon-ztp implementation, either part of aeon-ztp itself or an instance in our internal systest infrastructure.

c) Implementation of try/catch/retry types for getters and setters on the database model to simulate a blocking IO

d) Removal of API from standard nginx multi-threaded proxy and enforce a single thread for API (maybe?)

In any case, what is really needed is an explicit unit-test that can reproduce the problem.  This should occur with any three processes that access the database at the same time in any time period, which may be difficult to instantiate in a specific unit test.  We're testing functionality limitations of SQLite which are known (http://docs.sqlalchemy.org/en/rel_0_9/dialects/sqlite.html#database-locking-behavior-concurrency)

**Comment by bobbywatson3** [comment]
SQLAlchemy supports PostgreSQL. Should be trivial to swap it out on the back end. We'll get that in the next release.

Bobby

**Comment by jeremyschulman** [comment]
agreed that we should migrate to PostgreSQL.   Please open new ticket for that request; close/link this one.  Thank you.  @bobbywatson3

**Comment by bobbywatson3** [comment]
I tried duplicating this with concurrent post/delete/get scripts all running at the same time, but I was unable to. I'd like to be able to reliably duplicate this before I begin any work. @acarpi do you have a test you can share?

**Comment by acarpi** [comment]
@bobbywatson3  I'll follow up on this issue and try to give you a script to reproduce this issue by the end of the week.

**Comment by acarpi** [comment]
Hi,

I was able to dig a little bit more the problem, and I isolated the issue in the following steps that we are doing as part of our ZTP process in our testing infrastructure. 
1. In our sanitize scripts, we poll Aeon ZTP status for a box until its shows DONE
2. we trigger ZTP from a cumulus box, this invokes the /register/cumulus API at some point.

So it seems like the problem is associated with some timing between these two REST APIs.

I was able to successfully reproduce it doing the following:
1. From the Cumulus box: GET http://<aeon_ip>/api/register/cumulus, in loop, e.g. using the script
`while true; do wget -q -O /dev/null http://172.20.114.4/api/register/cumulus; [ "$?" -eq "0" ] || break; done`
2. From any other machine able to reach Aeon ZTP, GET http://<aeon_ip>/api/devices in loop,
`while true; do wget -q -O /dev/null http://172.20.114.4/api/devices; [ "$?" -eq "0" ] || break; done
`
Let it run for a few minutes (it took me a while to reproduce in my case). You'll find the error trace in /var/log/uwsgi/app/aeon-ztp.log

`admin@aeon-ztps:/var/log/uwsgi/app$ sudo cat aeon-ztp.log | grep "HTTP/1.1 500"
`
