### ISSUE TITLE
Mellanox SN2000 Cumulus license installation failure

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aeon-ztps#168]
Discussed with @bobbywatson3  - I will try to add troubleshooting information to this issue as soon as I can aquire logs, but license installation on Mellanox SN2000 cumulus switches failed with the ZTP scripts.

**Comment by jeremyschulman** [comment]
@jpsenior - ok, look forward to more information.

**Comment by acarpi** [comment]
problem is in ztp-cumulus.sh, we need to swap order between install_license and enable_mgmt_vrf .  Problem is the script should have failed, I'll keep looking

**Comment by jpsenior** [comment]
The wget fails as the management VRF is created within the bash script.  VRF context of the bash script has no visibility into the management VRF by the time install_license kicks in, and we can't change context of running scripts.

A simple fix is to just ensure license is installed first before applying management vrf

**Comment by jeremyschulman** [comment]
I believe the VRF setup should likely be removed from the ztp-cumulus.sh and moved to the "user specific" finalize step.

**Comment by bobbywatson3** [comment]
resolved in #174
