### ISSUE TITLE
How to apply DHCP reservation IP per mac

### ISSUE THREAD

**Issue by mmihir82** [Apstra/aeon-ztps#179]
Hello All,
I'm new to using Aeon-ZTP server. But I think this will help me to check which switch is ready. Its a great place for me to start. 
What I have currently setup in our environment: 
I'm running DHCP server with IP reservation by mac addr of the Cumulus Switch. So that when a Switch boots up grabs the IP via MAC address, then installs OS via ONIE and then run ZTP script which creates ansible user account on the switch, so that I can use ansible to push out the configuration. 

How to:
- With my current setup how to use Aeon-ZTP server with reserve IP per MAC.
- Then I like to run Ansible playbook, so that I don't have to run separately. 

Thank you for taking look at the request 
... I have already install Aeon-ZTP server, but having hard time to get things works such as:
Not seeing any logs on Web page,
API is not working, getting 501 error
And how to restart the aeon-ztp web server so that it able to reflect whats in the current directory and files on web page. 

Sorry, but that what I run into... love to explorer this Aeon-ZTP server.. 

Thank you

**Comment by jeremyschulman** [comment]
Hi @mmihir82 - Thank you for your interest and use with Aeon-ZTPS.  I will try to answer your questions.

The way I read your question, there are two parts:
1) setup of DHCP server
2) setup of Aeon-ZTPS to trigger Ansible playbook.

I'd like to tackle these separately.  I'll start with (2) because it's the easiest.  What you will need to do is the following:  on the aeon-ztps server, go to the directory cumulus profile directory:
````shell
admin@aeon-ztps:/opt/aeonztps/etc/profiles/default/cumulus$ ls
finally  os-selector.cfg
````

The `finally` script is executed once the Cumulus switch has booted up.  You can put anything you'd like in this finally script.  Just make sure that it's set for executable.   The Aeon-ZTPS framework will pass this script a number of environment variables that being with "AEON_".  For example "$AEON_TARGET" is the IP address of the Cumulus switch going through the Aeon-ZTPS process.  @bobbywatson3 is working on a comprehensive set of docs for writing a finally script; and hopefully it will get done very soon.

So to answer your question, you can run "ansible-playbook" from inside the finally script.  I hope this answers (2).  Please let me and and we can continue this discussion.  Thank you.

**Comment by jeremyschulman** [comment]
@mmihir82 - also; the default ztp-cumulus.sh script is here:
[https://github.com/Apstra/aeon-ztps/blob/master/ztp-scripts/ztp-cumulus.sh]

So if you want to change the default login username or password (currently: admin/admin), you can make your customizations there.  The file should be installed on your Aeon-ZTPS here:

````shell
admin@aeon-ztps:/opt/aeonztps/tftpboot$ ls
poap-md5sum  ztp-cumulus.sh  ztp-eos.sh  ztp-nxos.py
````

**Comment by mmihir82** [comment]
Wonderfull Jeremy, Thanks for answering.
To be clear, the file os-selector.cfg, I can add Mac-address with IP
Address? If so, Can you provide the example? thanks.

**Comment by jeremyschulman** [comment]
@mmihir82 - the os-selector.cfg file is used to tell Aeon-ZTPS which NOS version (i.e. Cumulus Linux version in this case) to ensure is installed on the device.  It does not control the IP address assignment.

I am assuming that you have an existing DHCP server that you are currently using for your IP address assignment.  You can continue to use it in the same way.  You will need to update your DHCP configuration to "point to" the Aeon-ZTPS server for downloading the Cumulus ztp script.   For example, we are using ISC-DHCP, and the configuration looks like this, note that the Aeon-ZTPS ip-address is "192.168.59.254" in this example:

````text
# The specific settings for Cumulus ONIE process
option cumulus-provision-url code 239 = text;

# this default-url *MUST* be in the global area for ONIE to
# work properly.  Not sure why this is, but it is.

option default-url = "http://192.168.59.254:8080/images/cumulus/onie-installer";

class "cumulus-switch" {
   match if (substring(option host-name, 0, 7) = "cumulus");
   option cumulus-provision-url "http://192.168.59.254:8080/downloads/ztp-cumulus.sh";
}
````

hope this helps.

**Comment by mmihir82** [comment]
Thanks Jeremy for explaining.. make sense now...

how to restart aeon-ztp server so that the web is been refreshed?

Thanks looking forward for the help doc.

Mihir M

**Comment by jeremyschulman** [comment]
@mmihir82 - if you are looking for a way to clear the Aeon-ZTPS database, from what you see on the UI page, you can login to the aeon-ztps and run the command:

````shell
aztp-db-flush
````

**Comment by mmihir82** [comment]
Hello Jermey,
Thanks for the info.

I don't get any DHCP offering...

My Current Running setup:
MacMini (running Ubuntu) >> running dhcp server >> all the switch gets the
ip thru reservation.

Using Aeon ZTP server:
MacMini (Mac OX) >> running vagrant with virtualbox with ETH1 ip
192.168.59.254 >> connected directly to the switch mgmt port... no dhcp
offering..
MacMini Physical ETH0: 68.140.xx.xx

Can you help?

Mihir M

**Comment by bobbywatson3** [comment]
Is the dhcp server running in the vagrant box? Can other devices on your network ping the IP of the ztps server? Are you seeing any incoming DHCP requests in the syslog of the DHCP server?

**Comment by bobbywatson3** [comment]
Please let us know if there's anything else we can do to help. Otherwise we'll close this issue in the next 24hrs.

**Comment by mmihir82** [comment]
Hello Bobby,
Sorry, I have not had time to work on the ZTP server.. I will work on it
what you have suggested. If I run into the error, I can msg you back.
