### ISSUE TITLE
user credentials for VirtualBox image

### ISSUE THREAD

**Issue by vnitinv** [Apstra/aeon-ztps#183]
I have created VirtualBox image referring http://aeon-ztps.readthedocs.io/en/latest/installation-guide/installation-guide.html#install-via-virtualbox

I am being prompted to enter user/password. Can't find any details in the documentation about this.

**Comment by bobbywatson3** [comment]
The login is admin/admin. I will update the docs to include that.

**Comment by bobbywatson3** [comment]
Also, if you're using vagrant, you don't need credentials. Just type `vagrant ssh`. I will add that to the documentation as well.
