### ISSUE TITLE
Aeon ZTP fails to install Cumulus license

### ISSUE THREAD

**Issue by acarpi** [Apstra/aeon-ztps#189]
Hi,

on a Cumulus physical box (tested on a Celestica Redstone XP) Aeon ZTP is failing to install the license as part of the autoprovisioning script ztp-cumulus.sh

The root cause is this condition
```
if [[ ! is_cumulus_vx ]]; then
   install_license
fi
```

which always tests negative, so the license installation was never executed. The check should rather be if [[ -n is_cumulus_vx ]]

**Comment by bobbywatson3** [comment]
Resolved by #190
