### ISSUE TITLE
ztp-cumulus bootstrap not working

### ISSUE THREAD

**Issue by mmihir82** [Apstra/aeon-ztps#196]
Hello All,
I have installed the ztp server, as follow: VirtualBox > ubuntu OS installed. Using only one NIC ETH0, which is accessible within the internal network. I'm using Dell S4048, the switch is able to get the DHCP IP and able to installed cumulus OS using ONIE. But I don't see anything in the "ZTP Status"

I'm missing bootstrap? how to configure it?

Thanks
Mihir M

**Comment by bobbywatson3** [comment]
Do you already have a DHCP server and ONIE server setup on the same network in addition to the ZTPS server?

AEON-ZTPS can either act as the DHCP server, or it can work with an external DHCP server. Either way, the DHCP conf should look similar to the example config file located here. https://github.com/Apstra/aeon-ztps/blob/master/install/roles/dhcp-server/files/aeon_ztps_example_dhcpd.conf

**Comment by mmihir82** [comment]
Hello bobby,
DHCP and ONIE are configured base on the example you provided, but I had to modified based on my requirement. 
Here is what my dhcp looks like:
**DHCPD.CONF**
```
ddns-update-style none;
default-lease-time 4320;
max-lease-time 8640;
ignore client-updates;
authoritative;
# Log to the local0 facility by default
log-facility local7;
include "/etc/dhcp/dhcpd.hosts";
include "/etc/dhcp/dell.cpld";
#option cumulus-provision-url code 239 = text;
allow booting;
allow bootp;
set vendorclass = option vendor-class-identifier;

subnet 10.50.20.128 netmask 255.255.255.128 {
	# Address that will not be allocated
	 range 10.50.20.202 10.50.20.203;
}
#################### NETS MGMT  ##################################
subnet 10.50.254.0 netmask 255.255.255.128 {
		range 10.50.254.67 10.50.254.80;
		option routers 10.50.254.1;
		option www-server 10.50.20.200;
		option tftp-server-name "10.50.20.200";
		option default-url "http://10.50.20.200/images/cumulus/onie-installer";
		option cumulus-provision-url "http://10.50.20.200/downloads/ztp-cumulus.sh";
}
```
ONIE file
```
option cumulus-provision-url code 239 = text;
option space onie code width 1 length width 1;
# Define the code names and data types within the ONIE namespace
option onie.installer_url code 1 = text;
option onie.updater_url   code 2 = text;
option onie.machine       code 3 = text;
option onie.arch          code 4 = text;
option onie.machine_rev   code 5 = text;
# Package the ONIE namespace into option 125
option space vivso code width 4 length width 1;
option vivso.onie code 42623 = encapsulate onie;
option vivso.iana code 0 = string;
option op125 code 125 = encapsulate vivso;
URL="http://10.50.20.200/"
class "onie-vendor-classes" {
  # Limit the matching to a request we know originated from ONIE
  match if substring(option vendor-class-identifier, 0, 11) = "onie_vendor";
  # Required to use VIVSO
  option vivso.iana 01:01:01;
  # matching on machine type
  if option onie.machine = "dell_s4048t_c2338" {
    option onie.installer_url = "$URL/images/cumulus/onie-installer";
    option cumulus-provision-url "$URL/downloads/ztp-cumulus.sh";
  }
}
```
I don't see any logs for bootstrap. Do I need to create bootstrap file for cumulus?

**Comment by bobbywatson3** [comment]
You will not need an ONIE server with AEON-ZTPS. You will not see bootstrap log entries if the switch does not download and execute ztp-cumulus.sh. In order to remove your DHCP server from troubleshooting, you can try manually invoking ztps from the cumulus switch itself. Type the following at the command line:

Cumulus 3:
`sudo ztp -v -r http://10.50.20.200/downloads/ztp-cumulus.sh`

Cumulus 2:
`sudo /usr/lib/cumulus/autoprovision -u http://10.50.20.200/downloads/ztp-cumulus.sh`

**Comment by mmihir82** [comment]
Hi 
I run the command you provided.. 
```
root@TEST-MLA6:~# ztp -v -r http://10.50.20.200/downloads/ztp-cumulus.sh
Attempting to provision via ZTP Manual from http://10.50.20.200/downloads/ztp-cumulus.sh

Broadcast message from admin@TEST-MLA6.oncue.verizon.net (pts/0) (Wed Apr

ZTP: Attempting to provision via ZTP Manual from http://10.50.20.200/downloads/
ztp-cumulus.sh
ZTP Manual: URL response code 200
ZTP Manual: Found Marker CUMULUS-AUTOPROVISIONING
ZTP Manual: Executing http://10.50.20.200/downloads/ztp-cumulus.sh

-------------------------------------
Aeon-ZTP auto-provision from: http://10.50.20.200
-------------------------------------

--2017-04-19 04:44:32--  http://10.50.20.200/downloads/cumulus/authorized_keys
Connecting to 10.50.20.200:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5434 (5.3K) [application/octet-stream]
Saving to: ‘/root/.ssh/authorized_keys’

/root/.ssh/authorized_ke 100%[====================================>]   5.31K  --.-KB/s   in 0s

2017-04-19 04:44:32 (133 MB/s) - ‘/root/.ssh/authorized_keys’ saved [5434/5434]

--2017-04-19 04:44:32--  http://10.50.20.200/downloads/cumulus/authorized_keys
Connecting to 10.50.20.200:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5434 (5.3K) [application/octet-stream]
Saving to: ‘/home/cumulus/.ssh/authorized_keys’

/home/cumulus/.ssh/autho 100%[====================================>]   5.31K  --.-KB/s   in 0s

2017-04-19 04:44:32 (358 MB/s) - ‘/home/cumulus/.ssh/authorized_keys’ saved [5434/5434]

useradd: user 'vzoncue' already exists
--2017-04-19 04:44:32--  http://10.50.20.200/downloads/cumulus/authorized_keys
Connecting to 10.50.20.200:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5434 (5.3K) [application/octet-stream]
Saving to: ‘/home/vzoncue/.ssh/authorized_keys’

/home/vzoncue/.ssh/autho 100%[====================================>]   5.31K  --.-KB/s   in 0s

2017-04-19 04:44:32 (298 MB/s) - ‘/home/vzoncue/.ssh/authorized_keys’ saved [5434/5434]

--2017-04-19 04:44:32--  http://10.50.20.200/api/register/cumulus
Connecting to 10.50.20.200:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0 [text/html]
Saving to: ‘/dev/null’

/dev/null                    [ <=>                                 ]       0  --.-KB/s   in 0s

2017-04-19 04:44:32 (0.00 B/s) - ‘/dev/null’ saved [0/0]

ZTP Manual: Script returned success
```

**Comment by mmihir82** [comment]
still, don't see in the ZTP status page

**Comment by bobbywatson3** [comment]
That is not the output from our ztp-cumulus.sh script. Is 10.50.20.200 the IP address of the AEON-ZTPS server?

**Comment by mmihir82** [comment]
correct

**Comment by bobbywatson3** [comment]
The ztp-cumulus.sh file that is being run by your device is not the ztp-cumulus.sh file that is used by aeon-ztps. If you want to have aeon-ztps perform the ZTP process, that aeon-ztps specific file has to be run.

aeon-ztps should be on its own dedicated VM. You might have something else running at 10.50.20.200 that is serving up the wrong ztp-cumulus.sh file.

**Comment by mmihir82** [comment]
Hello Bobby,
Only "ztp-cumulus.sh" is been using is from the dhcpd.conf file... so i remove it from their? In order to use AeonZTP? also like to run ansible role once the Switch is done installing OS.

**Comment by bobbywatson3** [comment]
The dhcpd.conf file must be pointing to the ztp-cumulus.sh file that is a part of aeon-ztps. It looks like you are using a different ztp-cumulus.sh file, so the aeon-ztp process will never begin.

**Comment by mmihir82** [comment]
Hello Bobby, 
Able to install and AeonZTP server successful. I can see those devices in status page. Thanks

Question: 
Is there any way to securely execute the ansible-playbook using ZTP Server base on Hostname? 
I have roles base on Function of the device. This would be really helpful to complete the automation. 

Thanks
Mihir M

**Comment by bobbywatson3** [comment]
Glad to hear you got it working.

I don't understand what you're asking about running the ansible playbook. Can you elaborate?

**Comment by bobbywatson3** [comment]
No response in three weeks. Closing issue.
