### ISSUE TITLE
Partial ZTP provisioning causes EOS to fail re-attempted ZTP reboots

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aeon-ztps#61]
If the device is in a 'failed' state on the ZTP database, or /api/register fails (eg, a device already exists) for reprovisioning/rebooting, the eos-bootstrap script will 'copy run start' anyway, thinking it is able to continue while the ZTP bootstrapper is running in the background waiting for device access.  

This causes a write to mnt/flash/startup-config for a ZTP-only 'bootstrap' configuration file to saved.  If a startup-config is present on bootup, ZTP doesn't run on the next reboot.

A condition like the below output files can cause some weirdness making it difficult/time consuming to resolve.

An example workflow that could reproduce this problem:
1) From a previously or partially registered EOS box, 'wr erase' and reload.
2) EOS will boot to ZTP, immediately download ztp-cumulus.sh from the DHCP provisioning URL
3) EOS will call /api/register/eos
4) EOS will 'wr mem' current config and reload to continue ZTP process.
4) Celery kicks off eos-bootstrap and waits for device access.
5) eos-bootstrap errors on 'unable to register device, already exists' and is unable to continue.
6) EOS box now has a partial ZTP configuration saved to startup-config and will not re-try ZTP.

Workaround:
1) Delete ZTP database entry for IP
2) Erase startup-config on EOS device
3) Reboot device and try ZTP again

[2016-09-17 01:19:43,952: ERROR/Worker-8] Unable to register device: device with os_name, ip_addr already exists
[2016-09-17 01:19:43,955: INFO/MainProcess] Task ztp_celery.ztp_bootstrapper[5595dfdb-5d5f-4c6c-b74d-8565aa9020c6] succeeded in 0.0247813040623s: 400
[2016-09-17 01:23:07,411: INFO/Worker-6] rc=1 stdout=
[2016-09-17 01:23:07,412: ERROR/Worker-6] stderr=Traceback (most recent call last):
  File "/opt/aeonztps/bin/eos-bootstrap", line 449, in <module>
    main()
  File "/opt/aeonztps/bin/eos-bootstrap", line 438, in main
    dev = wait_for_device(countdown=g_cli_args.reload_delay, poll_delay=10)
  File "/opt/aeonztps/bin/eos-bootstrap", line 195, in wait_for_device
    message='Failed to probe target %s within reload countdown' % target))
  File "/opt/aeonztps/bin/eos-bootstrap", line 139, in exit_results
    post_device_status(dev=dev, target=target, state='FAILED', message=results['message'])
  File "/opt/aeonztps/bin/eos-bootstrap", line 124, in post_device_status
    ip_addr=target or dev.target,
AttributeError: 'NoneType' object has no attribute 'target'

**Comment by jeremyschulman** [comment]
@bobbywatson3 - for next release, we need to at least fix the code so the backtrace issue is resolved.  this won't fix the issue reported; but need to make sure the code traps/reports correctly.

**Comment by bobbywatson3** [comment]
I don't know if this issue exists anymore. With PR #157, the ztp process will still attempt to run if the device is in an errored state. 

So if you kick off the ztp process, and there is an issue that puts it in an errored state, the next time you attempt a ztp boot, it will let it run again.

**Comment by bobbywatson3** [comment]
I just duplicated this, with the following steps:

1. Fresh EOS, not in ZTPS DB, write erase, reload
2. Device boots, but executing finally script failed due to EosSdk being unavailable on ZTPS.
3. Copy EosSdk to correct location on ZTPS
4. write erase and reload EOS switch (device was still in ERROR state in ZTPS. The device was not removed)
5. EOS device boots into ZTP mode and completes successfully.

I believe this issue to be resolved. @jpsenior if it is not, please let me know.
