### ISSUE TITLE
NXOS bootstrap program must check for virtual system to guardrail OS upgrade

### ISSUE THREAD

**Issue by jeremyschulman** [Apstra/aeon-ztps#75]
The nxos-bootstrap program does not guardrail against attempting to OS install on a vNXOS system.  Need to add a check / report / fail for this scenario.

**Comment by jpsenior** [comment]
@jeremyschulman can we expand os-selector.cfg to prevent this somehow?  Eg, disabled=True, with an explicit section mapping NXOSv as a model?  For example, your suggestion in https://github.com/Apstra/aeon-ztps/issues/130
